//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Expiration Date.
        /// </summary>
        internal static string _ExpirationDate {
            get {
                return ResourceManager.GetString("*ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment:.
        /// </summary>
        internal static string AddAComment_ {
            get {
                return ResourceManager.GetString("AddAComment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pictures of the tour:.
        /// </summary>
        internal static string AddPicturesOfTheTour_ {
            get {
                return ResourceManager.GetString("AddPicturesOfTheTour:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tour segment.
        /// </summary>
        internal static string AddTourSegment {
            get {
                return ResourceManager.GetString("AddTourSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance:.
        /// </summary>
        internal static string Attendance_ {
            get {
                return ResourceManager.GetString("Attendance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be creative!.
        /// </summary>
        internal static string BeCreative_ {
            get {
                return ResourceManager.GetString("BeCreative!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now!.
        /// </summary>
        internal static string BookNow_ {
            get {
                return ResourceManager.GetString("BookNow!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book tour!.
        /// </summary>
        internal static string BookTour_ {
            get {
                return ResourceManager.GetString("BookTour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoints:.
        /// </summary>
        internal static string Checkpoints_ {
            get {
                return ResourceManager.GetString("Checkpoints:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a voucher if available:.
        /// </summary>
        internal static string ChooseAVoucherIfAvailable_ {
            get {
                return ResourceManager.GetString("ChooseAVoucherIfAvailable:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a year:.
        /// </summary>
        internal static string ChooseAYear_ {
            get {
                return ResourceManager.GetString("ChooseAYear:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your tour!.
        /// </summary>
        internal static string ChooseYourTour_ {
            get {
                return ResourceManager.GetString("ChooseYourTour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex request details.
        /// </summary>
        internal static string ComplexRequestDetails {
            get {
                return ResourceManager.GetString("ComplexRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex tour request.
        /// </summary>
        internal static string ComplexTourRequest {
            get {
                return ResourceManager.GetString("ComplexTourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Country_ {
            get {
                return ResourceManager.GetString("Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        internal static string CreationDate_ {
            get {
                return ResourceManager.GetString("CreationDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address:.
        /// </summary>
        internal static string CurrentAddress_ {
            get {
                return ResourceManager.GetString("CurrentAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current checkpoint:.
        /// </summary>
        internal static string CurrentCheckpoint_ {
            get {
                return ResourceManager.GetString("CurrentCheckpoint:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date:.
        /// </summary>
        internal static string DepartureDate_ {
            get {
                return ResourceManager.GetString("DepartureDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time:.
        /// </summary>
        internal static string DepartureTime_ {
            get {
                return ResourceManager.GetString("DepartureTime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description_ {
            get {
                return ResourceManager.GetString("Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        internal static string Destination_ {
            get {
                return ResourceManager.GetString("Destination:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver:.
        /// </summary>
        internal static string Driver_ {
            get {
                return ResourceManager.GetString("Driver:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive reservation.
        /// </summary>
        internal static string DriveReservation {
            get {
                return ResourceManager.GetString("DriveReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Duration_ {
            get {
                return ResourceManager.GetString("Duration:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration span:.
        /// </summary>
        internal static string DurationSpan_ {
            get {
                return ResourceManager.GetString("DurationSpan:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string EndDate_ {
            get {
                return ResourceManager.GetString("EndDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of guests:.
        /// </summary>
        internal static string EnterTheNumberOfGuests_ {
            get {
                return ResourceManager.GetString("EnterTheNumberOfGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date:.
        /// </summary>
        internal static string ExpirationDate_ {
            get {
                return ResourceManager.GetString("ExpirationDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast drive reservation.
        /// </summary>
        internal static string FastDriveReservation {
            get {
                return ResourceManager.GetString("FastDriveReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to be late?.
        /// </summary>
        internal static string GoingToBeLate_ {
            get {
                return ResourceManager.GetString("GoingToBeLate?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go interesting ideas for complex tours?.
        /// </summary>
        internal static string GotInterestingIdeasForComplexTours_ {
            get {
                return ResourceManager.GetString("GotInterestingIdeasForComplexTours?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got interesting ideas for new tours?.
        /// </summary>
        internal static string GotInterestingIdeasForNewTour_ {
            get {
                return ResourceManager.GetString("GotInterestingIdeasForNewTour?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group drive reservation.
        /// </summary>
        internal static string GroupDriveReservation {
            get {
                return ResourceManager.GetString("GroupDriveReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its never a bad idea to save money!.
        /// </summary>
        internal static string ItsNeverABadIdeaToSaveMoney_ {
            get {
                return ResourceManager.GetString("ItsNeverABadIdeaToSaveMoney!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname:.
        /// </summary>
        internal static string Lastname_ {
            get {
                return ResourceManager.GetString("Lastname:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your reservation.
        /// </summary>
        internal static string MakeYourReservation {
            get {
                return ResourceManager.GetString("MakeYourReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum guests:.
        /// </summary>
        internal static string MaximumGuests_ {
            get {
                return ResourceManager.GetString("MaximumGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes late.
        /// </summary>
        internal static string MinutesLate {
            get {
                return ResourceManager.GetString("MinutesLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My complex tour requests.
        /// </summary>
        internal static string MyComplexTourRequests {
            get {
                return ResourceManager.GetString("MyComplexTourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My drive reservations.
        /// </summary>
        internal static string MyDriveReservations {
            get {
                return ResourceManager.GetString("MyDriveReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My drive reservations:.
        /// </summary>
        internal static string MyDriveReservations_ {
            get {
                return ResourceManager.GetString("MyDriveReservations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My drives.
        /// </summary>
        internal static string MyDrives {
            get {
                return ResourceManager.GetString("MyDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My statistics.
        /// </summary>
        internal static string MyStatistics {
            get {
                return ResourceManager.GetString("MyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tour requests.
        /// </summary>
        internal static string MyTourRequests {
            get {
                return ResourceManager.GetString("MyTourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tour reservations.
        /// </summary>
        internal static string MyTourReservations {
            get {
                return ResourceManager.GetString("MyTourReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        internal static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        internal static string NumberOfGuests_ {
            get {
                return ResourceManager.GetString("NumberOfGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of passengers:.
        /// </summary>
        internal static string NumberOfPassengers_ {
            get {
                return ResourceManager.GetString("NumberOfPassengers:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people:.
        /// </summary>
        internal static string NumberOfPeople_ {
            get {
                return ResourceManager.GetString("NumberOfPeople:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of accepted tours:.
        /// </summary>
        internal static string PercentageOfAcceptedTours_ {
            get {
                return ResourceManager.GetString("PercentageOfAcceptedTours:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of cancelled tours:.
        /// </summary>
        internal static string PercentageOfCancelledTours_ {
            get {
                return ResourceManager.GetString("PercentageOfCancelledTours:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the tour:.
        /// </summary>
        internal static string RateTheTour_ {
            get {
                return ResourceManager.GetString("RateTheTour:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate tour.
        /// </summary>
        internal static string RateTour {
            get {
                return ResourceManager.GetString("RateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate tour!.
        /// </summary>
        internal static string RateTour_ {
            get {
                return ResourceManager.GetString("RateTour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request statistics.
        /// </summary>
        internal static string RequestStatistics {
            get {
                return ResourceManager.GetString("RequestStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve drive!.
        /// </summary>
        internal static string ReserveDrive_ {
            get {
                return ResourceManager.GetString("ReserveDrive!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date and time:.
        /// </summary>
        internal static string SelectTheDateAndTime_ {
            get {
                return ResourceManager.GetString("SelectTheDateAndTime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start address:.
        /// </summary>
        internal static string StartAddress_ {
            get {
                return ResourceManager.GetString("StartAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string StartDate_ {
            get {
                return ResourceManager.GetString("StartDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting time:.
        /// </summary>
        internal static string StartingTime_ {
            get {
                return ResourceManager.GetString("StartingTime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting times:.
        /// </summary>
        internal static string StartingTimes_ {
            get {
                return ResourceManager.GetString("StartingTimes:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status_ {
            get {
                return ResourceManager.GetString("Status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string Street_ {
            get {
                return ResourceManager.GetString("Street:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guide set the time:.
        /// </summary>
        internal static string TheGuideSetTheTime_ {
            get {
                return ResourceManager.GetString("TheGuideSetTheTime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more the merrier!.
        /// </summary>
        internal static string TheMoreTheMerrier_ {
            get {
                return ResourceManager.GetString("TheMoreTheMerrier!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time_ {
            get {
                return ResourceManager.GetString("Time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour guests:.
        /// </summary>
        internal static string TourGuests_ {
            get {
                return ResourceManager.GetString("TourGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour request.
        /// </summary>
        internal static string TourRequest {
            get {
                return ResourceManager.GetString("TourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour segment.
        /// </summary>
        internal static string TourSegment {
            get {
                return ResourceManager.GetString("TourSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour tracking.
        /// </summary>
        internal static string TourTracking {
            get {
                return ResourceManager.GetString("TourTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track tour.
        /// </summary>
        internal static string TrackTour {
            get {
                return ResourceManager.GetString("TrackTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreliable driver.
        /// </summary>
        internal static string UnreliableDriver {
            get {
                return ResourceManager.GetString("UnreliableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used: ✔️.
        /// </summary>
        internal static string Used_ {
            get {
                return ResourceManager.GetString("Used:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used: ❌.
        /// </summary>
        internal static string Usedx_ {
            get {
                return ResourceManager.GetString("Usedx:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Username_ {
            get {
                return ResourceManager.GetString("Username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid: ✔️.
        /// </summary>
        internal static string Valid_ {
            get {
                return ResourceManager.GetString("Valid:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid: ❌.
        /// </summary>
        internal static string Validx_ {
            get {
                return ResourceManager.GetString("Validx:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View gallery.
        /// </summary>
        internal static string ViewGallery {
            get {
                return ResourceManager.GetString("ViewGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We appreciate feedback!.
        /// </summary>
        internal static string WeAppreciateFeedback_ {
            get {
                return ResourceManager.GetString("WeAppreciateFeedback!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to go?.
        /// </summary>
        internal static string WhereDoYouWantToGo_ {
            get {
                return ResourceManager.GetString("WhereDoYouWantToGo?", resourceCulture);
            }
        }
    }
}
