//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Datum isteka.
        /// </summary>
        internal static string _ExpirationDate {
            get {
                return ResourceManager.GetString("*Expiration date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odsutan.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj komentar:.
        /// </summary>
        internal static string Add_a_comment_ {
            get {
                return ResourceManager.GetString("Add a comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slike ture:.
        /// </summary>
        internal static string Add_pictures_of_the_tour_ {
            get {
                return ResourceManager.GetString("Add pictures of the tour:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj segment ture.
        /// </summary>
        internal static string Add_tour_segment {
            get {
                return ResourceManager.GetString("Add tour segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo:.
        /// </summary>
        internal static string Attendance_ {
            get {
                return ResourceManager.GetString("Attendance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budi kreativan!.
        /// </summary>
        internal static string Be_creative_ {
            get {
                return ResourceManager.GetString("Be creative!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži odmah!.
        /// </summary>
        internal static string Book_now_ {
            get {
                return ResourceManager.GetString("Book now!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži turu!.
        /// </summary>
        internal static string Book_tour_ {
            get {
                return ResourceManager.GetString("Book tour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tačke ture:.
        /// </summary>
        internal static string Checkpoints_ {
            get {
                return ResourceManager.GetString("Checkpoints:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi vaučer ako imaš:.
        /// </summary>
        internal static string Choose_a_voucher_if_available_ {
            get {
                return ResourceManager.GetString("Choose a voucher if available:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi svoju turu!.
        /// </summary>
        internal static string Choose_your_tour_ {
            get {
                return ResourceManager.GetString("Choose your tour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji složenog zahtjeva.
        /// </summary>
        internal static string Complex_request_details {
            get {
                return ResourceManager.GetString("Complex request details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složeni zahtjev ture.
        /// </summary>
        internal static string Complex_tour_request {
            get {
                return ResourceManager.GetString("Complex tour request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država:.
        /// </summary>
        internal static string Country_ {
            get {
                return ResourceManager.GetString("Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja:.
        /// </summary>
        internal static string Creation_date_ {
            get {
                return ResourceManager.GetString("Creation date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna adresa:.
        /// </summary>
        internal static string Current_address_ {
            get {
                return ResourceManager.GetString("Current address:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna tačka ture:.
        /// </summary>
        internal static string Current_checkpoint_ {
            get {
                return ResourceManager.GetString("Current checkpoint:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum polaska:.
        /// </summary>
        internal static string Departure_date_ {
            get {
                return ResourceManager.GetString("Departure date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme polaska:.
        /// </summary>
        internal static string Departure_time_ {
            get {
                return ResourceManager.GetString("Departure time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        internal static string Description_ {
            get {
                return ResourceManager.GetString("Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinacija:.
        /// </summary>
        internal static string Destination_ {
            get {
                return ResourceManager.GetString("Destination:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija vožnje.
        /// </summary>
        internal static string Drive_reservation {
            get {
                return ResourceManager.GetString("Drive reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozač:.
        /// </summary>
        internal static string Driver_ {
            get {
                return ResourceManager.GetString("Driver:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje:.
        /// </summary>
        internal static string Duration_ {
            get {
                return ResourceManager.GetString("Duration:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspon trajanja:.
        /// </summary>
        internal static string Duration_span_ {
            get {
                return ResourceManager.GetString("Duration span:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajnji datum:.
        /// </summary>
        internal static string End_date_ {
            get {
                return ResourceManager.GetString("End date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi broj gostiju:.
        /// </summary>
        internal static string Enter_the_number_of_guests_ {
            get {
                return ResourceManager.GetString("Enter the number of guests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum isteka:.
        /// </summary>
        internal static string Expiration_date_ {
            get {
                return ResourceManager.GetString("Expiration date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galerija.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idi nazad.
        /// </summary>
        internal static string Go_back {
            get {
                return ResourceManager.GetString("Go back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakasnićeš?.
        /// </summary>
        internal static string Going_to_be_late_ {
            get {
                return ResourceManager.GetString("Going to be late?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaš interesantne ideje za složene ture?.
        /// </summary>
        internal static string Got_interesting_ideas_for_complex_tours_ {
            get {
                return ResourceManager.GetString("Got interesting ideas for complex tours?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaš interesantne ideje za nove ture?.
        /// </summary>
        internal static string Got_interesting_ideas_for_new_tour_ {
            get {
                return ResourceManager.GetString("Got interesting ideas for new tour?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        internal static string Home_page {
            get {
                return ResourceManager.GetString("Home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikad nije loša ideja uštediti novac!.
        /// </summary>
        internal static string It_s_never_a_bad_idea_to_save_money_ {
            get {
                return ResourceManager.GetString("It\'s never a bad idea to save money!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        internal static string Lastname_ {
            get {
                return ResourceManager.GetString("Lastname:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi svoju rezervaciju.
        /// </summary>
        internal static string Make_your_reservation {
            get {
                return ResourceManager.GetString("Make your reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maks. broj gostiju:.
        /// </summary>
        internal static string Maximum_guests_ {
            get {
                return ResourceManager.GetString("Maximum guests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji složeni zahtjevi tura.
        /// </summary>
        internal static string My_complex_tour_requests {
            get {
                return ResourceManager.GetString("My complex tour requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje rezervacije vožnji:.
        /// </summary>
        internal static string My_drive_reservations_ {
            get {
                return ResourceManager.GetString("My drive reservations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moj profil.
        /// </summary>
        internal static string My_profile {
            get {
                return ResourceManager.GetString("My profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje rezervacije.
        /// </summary>
        internal static string My_reservations {
            get {
                return ResourceManager.GetString("My reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji zahtjevi tura.
        /// </summary>
        internal static string My_tour_requests {
            get {
                return ResourceManager.GetString("My tour requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje rezervacije tura.
        /// </summary>
        internal static string My_tour_reservations {
            get {
                return ResourceManager.GetString("My tour reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi zahtjev.
        /// </summary>
        internal static string New_request {
            get {
                return ResourceManager.GetString("New request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeća.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju:.
        /// </summary>
        internal static string Number_of_guests_ {
            get {
                return ResourceManager.GetString("Number of guests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj putnika:.
        /// </summary>
        internal static string Number_of_passengers_ {
            get {
                return ResourceManager.GetString("Number of passengers:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ljudi:.
        /// </summary>
        internal static string Number_of_people_ {
            get {
                return ResourceManager.GetString("Number of people:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisutan.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilna slika.
        /// </summary>
        internal static string Profile_picture {
            get {
                return ResourceManager.GetString("Profile picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni turu:.
        /// </summary>
        internal static string Rate_the_tour_ {
            get {
                return ResourceManager.GetString("Rate the tour:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni turu.
        /// </summary>
        internal static string Rate_tour {
            get {
                return ResourceManager.GetString("Rate tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni turu!.
        /// </summary>
        internal static string Rate_tour_ {
            get {
                return ResourceManager.GetString("Rate tour!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj statistiku.
        /// </summary>
        internal static string Request_statistics {
            get {
                return ResourceManager.GetString("Request statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerviši vožnju!.
        /// </summary>
        internal static string Reserve_drive_ {
            get {
                return ResourceManager.GetString("Reserve drive!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidi više.
        /// </summary>
        internal static string See_more {
            get {
                return ResourceManager.GetString("See more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi datum i vrijeme:.
        /// </summary>
        internal static string Select_the_date_and_time_ {
            get {
                return ResourceManager.GetString("Select the date and time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna adresa:.
        /// </summary>
        internal static string Start_address_ {
            get {
                return ResourceManager.GetString("Start address:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datum:.
        /// </summary>
        internal static string Start_date_ {
            get {
                return ResourceManager.GetString("Start date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početno vrijeme:.
        /// </summary>
        internal static string Starting_time_ {
            get {
                return ResourceManager.GetString("Starting time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni termini:.
        /// </summary>
        internal static string Starting_times_ {
            get {
                return ResourceManager.GetString("Starting times:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status_ {
            get {
                return ResourceManager.GetString("Status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica:.
        /// </summary>
        internal static string Street_ {
            get {
                return ResourceManager.GetString("Street:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodič je zakazao vrijeme:.
        /// </summary>
        internal static string The_guide_set_the_time_ {
            get {
                return ResourceManager.GetString("The guide set the time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Što više to, to veselije!.
        /// </summary>
        internal static string The_more_the_merrier_ {
            get {
                return ResourceManager.GetString("The more the merrier!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme:.
        /// </summary>
        internal static string Time_ {
            get {
                return ResourceManager.GetString("Time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosti ture:.
        /// </summary>
        internal static string Tour_guests_ {
            get {
                return ResourceManager.GetString("Tour guests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev ture.
        /// </summary>
        internal static string Tour_request {
            get {
                return ResourceManager.GetString("Tour request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment ture.
        /// </summary>
        internal static string Tour_segment {
            get {
                return ResourceManager.GetString("Tour segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praćenje ture.
        /// </summary>
        internal static string Tour_tracking {
            get {
                return ResourceManager.GetString("Tour tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prati turu.
        /// </summary>
        internal static string Track_tour {
            get {
                return ResourceManager.GetString("Track tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepouzdan vozač.
        /// </summary>
        internal static string Unreliable_driver {
            get {
                return ResourceManager.GetString("Unreliable driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskorišten:.
        /// </summary>
        internal static string Used_ {
            get {
                return ResourceManager.GetString("Used:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string Username_ {
            get {
                return ResourceManager.GetString("Username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validan:.
        /// </summary>
        internal static string Valid_ {
            get {
                return ResourceManager.GetString("Valid:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj galeriju.
        /// </summary>
        internal static string ViewGallery {
            get {
                return ResourceManager.GetString("View gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cijenimo vaše mišljenje!.
        /// </summary>
        internal static string We_appreciate_feedback_ {
            get {
                return ResourceManager.GetString("We appreciate feedback!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdje želiš da ideš?.
        /// </summary>
        internal static string Where_do_you_want_to_go_ {
            get {
                return ResourceManager.GetString("Where do you want to go?", resourceCulture);
            }
        }
    }
}
